---
openapi: 3.1.0
components:
  schemas:
    Artist:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createDate:
          $ref: "#/components/schemas/LocalDateTime"
        name:
          type: string
        lastfmUri:
          type: string
        spotifyUri:
          type: string
        musicbrainzId:
          type: string
        followerCount:
          type: integer
          format: int32
        spotifyUriId:
          type: string
    ArtistDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lastfmUri:
          type: string
        spotifyUri:
          type: string
        musicbrainzId:
          type: string
        followerCount:
          type: integer
          format: int32
    ArtistSearchResponse:
      type: object
      properties:
        count:
          type: integer
          format: int32
        artists:
          type: array
          items:
            $ref: "#/components/schemas/SearchResultArtistDto"
    FollowedArtistsRelease:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
        spotifyUri:
          type: string
        musicbrainzId:
          type: string
        releasedOn:
          $ref: "#/components/schemas/LocalDate"
        artists:
          type: array
          items:
            $ref: "#/components/schemas/ArtistDto"
    FollowedArtistsReleaseResponse:
      type: object
      properties:
        total:
          type: integer
          format: int32
        releases:
          type: array
          items:
            $ref: "#/components/schemas/FollowedArtistsRelease"
    FollowedArtistsResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
        rows:
          type: array
          items:
            $ref: "#/components/schemas/ArtistDto"
    LocalDate:
      type: string
      format: date
      examples:
        - 2022-03-10
    LocalDateTime:
      type: string
      format: date-time
      examples:
        - 2022-03-10T12:15:50
    RaccoonUser:
      type: object
      required:
        - email
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        username:
          type: string
        lastfmUsername:
          type: string
        spotifyEnabled:
          type: boolean
        lastNotified:
          $ref: "#/components/schemas/LocalDate"
        createDate:
          $ref: "#/components/schemas/LocalDateTime"
        modifyDate:
          $ref: "#/components/schemas/LocalDateTime"
        lastSpotifyScrape:
          $ref: "#/components/schemas/LocalDateTime"
        lastLastFmScrape:
          $ref: "#/components/schemas/LocalDateTime"
    RegisterUserRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
        lastfmUsername:
          type: string
        spotifyEnabled:
          type: boolean
    Release:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
        spotifyUri:
          type: string
        musicbrainzId:
          type: string
        releasedOn:
          $ref: "#/components/schemas/LocalDate"
    ReleaseScrapeResponse:
      type: object
      properties:
        scrape:
          $ref: "#/components/schemas/Scrape"
    Scrape:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createDate:
          $ref: "#/components/schemas/LocalDateTime"
        modifyDate:
          $ref: "#/components/schemas/LocalDateTime"
        completeDate:
          $ref: "#/components/schemas/LocalDateTime"
        releasesFromSpotify:
          type: integer
          format: int64
        releasesFromMusicbrainz:
          type: integer
          format: int64
        releaseCount:
          type: integer
          format: int32
        usersNotified:
          type: integer
          format: int64
        relevantReleases:
          type: integer
          format: int64
        isComplete:
          type: boolean
        releases:
          type: array
          items:
            $ref: "#/components/schemas/Release"
    SearchResultArtistDto:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lastfmUri:
          type: string
        spotifyUri:
          type: string
        musicbrainzId:
          type: string
        followedByUser:
          type: boolean
        followerCount:
          type: integer
          format: int32
    SpotifyAuth:
      type: object
      properties:
        code:
          type: string
        state:
          type: string
    UserArtist:
      type: object
      properties:
        weight:
          type: number
          format: float
        hasNewRelease:
          type: boolean
        user:
          $ref: "#/components/schemas/RaccoonUser"
          type: object
          writeOnly: true
        artist:
          $ref: "#/components/schemas/Artist"
          type: object
          writeOnly: true
    UserProfile:
      type: object
      properties:
        id:
          type: string
        spotifyEnabled:
          type: boolean
        lastfmUsername:
          type: string
        unsubscribed:
          type: boolean
        notifyIntervalDays:
          type: integer
          format: int32
    UserSettings:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user:
          $ref: "#/components/schemas/RaccoonUser"
        notifyIntervalDays:
          type: integer
          format: int32
        unsubscribed:
          type: boolean
    UserSettingsDto:
      type: object
      properties:
        notifyIntervalDays:
          type: integer
          format: int32
        unsubscribed:
          type: boolean
  securitySchemes:
    SecurityScheme:
      type: openIdConnect
      openIdConnectUrl: https://rr-dev.eu.auth0.com/.well-known/openid-configuration
      description: Authentication
paths:
  /:
    get:
      responses:
        "200":
          description: OK
      summary: Index
      tags:
        - Index Resource
  /artist/search:
    get:
      parameters:
        - name: pattern
          in: query
          schema:
            type: string
        - name: size
          in: query
          schema:
            type: integer
            format: int32
          required: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArtistSearchResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Search Artists
      tags:
        - Artist Search Resource
      security:
        - SecurityScheme: []
  /artists:
    get:
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 0
            minimum: 0
        - name: size
          in: query
          schema:
            type: integer
            exclusiveMinimum: 0
            format: int32
            default: 10
            maximum: 100
      responses:
        "200":
          description: OK
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get All
      tags:
        - Artist Resource
      security:
        - SecurityScheme: []
  /artists/recommended:
    get:
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 0
            minimum: 0
        - name: size
          in: query
          schema:
            type: integer
            exclusiveMinimum: 0
            format: int32
            default: 10
            maximum: 100
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FollowedArtistsResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Recommended Artists
      tags:
        - Artist Resource
      security:
        - SecurityScheme: []
  /me:
    get:
      parameters:
        - name: redirectUrl
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Registration Callback
      tags:
        - User Profile Resource
      security:
        - SecurityScheme: []
  /me/enable-services:
    get:
      parameters:
        - name: enableSpotify
          in: query
          schema:
            type: boolean
          required: false
        - name: lastfmUsername
          in: query
          schema:
            type: string
          required: false
      responses:
        "200":
          description: OK
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Enable Taste Sources
      tags:
        - User Profile Resource
      security:
        - SecurityScheme: []
  /me/follow:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchResultArtistDto"
        required: true
      responses:
        "200":
          description: OK
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
        "400":
          description: Bad Request
      summary: Follow Artist
      tags:
        - User Profile Resource
      security:
        - SecurityScheme: []
  /me/followed-artists:
    get:
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            format: int32
          required: false
        - name: size
          in: query
          schema:
            type: integer
            format: int32
          required: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FollowedArtistsResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Followed Artists
      tags:
        - User Profile Resource
      security:
        - SecurityScheme: []
  /me/followed-artists/releases:
    get:
      parameters:
        - name: days
          in: query
          schema:
            type: integer
            format: int32
          required: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FollowedArtistsReleaseResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Followed Artists Releases
      tags:
        - User Profile Resource
      security:
        - SecurityScheme: []
  /me/profile:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get User Profile
      tags:
        - User Profile Resource
      security:
        - SecurityScheme: []
  /me/settings:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSettings"
        required: true
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Set User Settings
      tags:
        - User Settings Resource
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSettingsDto"
      summary: Get User Settings
      tags:
        - User Settings Resource
  /me/unfollow/{artistId}:
    delete:
      parameters:
        - name: artistId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Unfollow Artist
      tags:
        - User Profile Resource
      security:
        - SecurityScheme: []
  /notify-users:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: boolean
      summary: Notify Users
      tags:
        - Notifying Resource
  /release-scrape:
    put:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReleaseScrapeResponse"
      summary: Scrape Releases
      tags:
        - Release Scrape Resource
  /scrape-taste/lastfm:
    parameters:
      - name: email
        in: query
        schema:
          type: string
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserArtist"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Scrape Lastfm Taste
      tags:
        - Taste Scraping Resource
      security:
        - SecurityScheme: []
  /scrape-taste/spotify:
    parameters:
      - name: email
        in: query
        schema:
          type: string
    get:
      responses:
        "200":
          description: OK
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Scrape Spotify Taste Web App
      tags:
        - Taste Scraping Resource
      security:
        - SecurityScheme: []
  /scrape-taste/spotify/client-auth:
    parameters:
      - name: email
        in: query
        schema:
          type: string
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpotifyAuth"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserArtist"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
        "400":
          description: Bad Request
      summary: Scrape Spotify Taste Client Auth
      tags:
        - Taste Scraping Resource
      security:
        - SecurityScheme: []
  /spotify-auth-callback:
    get:
      parameters:
        - name: code
          in: query
          schema:
            type: string
        - name: error
          in: query
          schema:
            type: string
        - name: state
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
      summary: Complete Auth
      tags:
        - Spotify Auth Resource
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Authorize Spotify
      tags:
        - Spotify Auth Resource
  /spotify-auth-callback/user-top-artists:
    get:
      parameters:
        - name: userId
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
      summary: Get User Top Artists
      tags:
        - Spotify Auth Resource
  /stats:
    get:
      responses:
        "200":
          description: OK
      summary: Get All Stats
      tags:
        - Stats Resource
  /stats/artists/count:
    get:
      responses:
        "200":
          description: OK
      summary: Get Artist Count
      tags:
        - Stats Resource
  /stats/releases/count:
    get:
      responses:
        "200":
          description: OK
      summary: Get Release Count
      tags:
        - Stats Resource
info:
  title: release-raccoon-app API
  version: 0.5.1-SNAPSHOT
